fixes raises with `var T` (#1405)
```nim
proc `[]`*[K: Keyable, V](t: Table[K, V]; k: K): var V {.raises.} =
  let idx = rawGet(t, k, hash(k))
  if idx < 0:
    raise KeyError
  t.data[idx][1]
```

For a `var T` return type, we cannot use `getType` because it is a `var
T` instead of `ptr T` returned by `getType`


```c
nimcache/ttauegnb4.c:583:12: error: assigning to 'AtupleSX45rrorX43ode0sysvq0aslAmutAiS64_0_t' (aka 'struct AtupleSX45rrorX43ode0sysvq0aslAmutAiS64_0_t') from incompatible type 'AtupleSX45rrorX43ode0sysvq0aslAptrAiS64_0_t' (aka 'struct AtupleSX45rrorX43ode0sysvq0aslAptrAiS64_0_t')
  583 |   result_2 = (AtupleSX45rrorX43ode0sysvq0aslAptrAiS64_0_t){
      |            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  584 |     .fld_0 = Success_0_sysvq0asl, .fld_1 = (&(*getQ_2_ttauegnb4(t_2.data_0_I8uyrpu, IL64(0))).fld_1)}
```